networks:
  reverse-proxy:
    external: true
services:
  service:
    image: nginx:1.25-bookworm
    networks:
      reverse-proxy:
        aliases:
          - nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
version: "3.8"
